version: "3"

services:
  playbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    volumes:
      - .:/app
    container_name: playbook
    networks:
      - playbook

  p_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: p_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - playbook

  p_kibana:
    container_name: p_kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://p_elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - p_elasticsearch
    networks:
      - playbook

  ## MySQL
  playbook-db:
    container_name: playbook-db
    image: mysql:5.7
    volumes:
      - playbook_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=playbook
      - MYSQL_USER=playbookUser
      - MYSQL_PASSWORD=playbookPassword
    ports:
      - "3306:3306"
    networks:
      - playbook

networks:
  playbook:
    external:
      name: playbook

volumes:
  playbook_db: {}
  elasticsearch-data:
    driver: local